name: Go lint

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Lint
      run: make lint

    - name: Vet
      run: make vet
